# Ingresses for Kong API Gateway to talk to the Admin APIs

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: simulators-rewrite
config:
  replace:
    uri: "/$(uri_captures[1])"
plugin: request-transformer
---
apiVersion: extensions/v1beta1 
kind: Ingress
metadata:
  name: simulators
  annotations:
    kubernetes.io/ingress.class: kong
    # konghq.com/strip-path: "true"
    # This is required to rewrite paths to services that contain multiple endpoints, 
    # e.g. /participants and /parties are both on the account-lookup-service
    konghq.com/plugins: simulators-rewrite
spec:
  rules:
    - http:
        paths:
          # dfspa - path based
          - path: /dfspa/simulator/(.*)
            backend:
              serviceName: dfspa-mojaloop-simulator
              servicePort: 3003
          - path: /dfspa/sdk-scheme-adapter/(.*)
            backend:
              serviceName: dfspa-sdk-scheme-adapter
              servicePort: 4000
          - path: /dfspa/thirdparty-scheme-adapter/inbound/(.*)
            backend:
              serviceName: dfspa-thirdparty-scheme-adapter
              servicePort: 4005
          - path: /dfspa/thirdparty-scheme-adapter/outbound/(.*)
            backend:
              serviceName: dfspa-thirdparty-scheme-adapter
              servicePort: 4006

          # dfspb - path based
          - path: /dfspb/simulator/(.*)
            backend:
              serviceName: dfspb-mojaloop-simulator
              servicePort: 3003
          - path: /dfspb/sdk-scheme-adapter/(.*)
            backend:
              serviceName: dfspb-sdk-scheme-adapter
              servicePort: 4000
          - path: /dfspb/thirdparty-scheme-adapter/inbound/(.*)
            backend:
              serviceName: dfspb-thirdparty-scheme-adapter
              servicePort: 4005
          - path: /dfspb/thirdparty-scheme-adapter/outbound/(.*)
            backend:
              serviceName: dfspb-thirdparty-scheme-adapter
              servicePort: 4006

          # pispa - path based
          - path: /pispa/thirdparty-scheme-adapter/inbound/(.*)
            backend:
              serviceName: pispa-thirdparty-scheme-adapter
              servicePort: 4005
          - path: /pispa/thirdparty-scheme-adapter/outbound/(.*)
            backend:
              serviceName: pispa-thirdparty-scheme-adapter
              servicePort: 4006